export const SUB_STORE_KEY_SELECTED_ENTITY = 'selectedEntity';
export const SUB_STORE_KEY_ENTITIES        = 'entities';

export const ENTITY_STORE_STATUS_INITIAL    = 'initial';
export const ENTITY_STORE_STATUS_LOADING    = 'loading';
export const ENTITY_STORE_STATUS_LOADED     = 'loaded';
export const ENTITY_STORE_STATUS_SAVING     = 'saving';
export const ENTITY_STORE_STATUS_SAVED      = 'saved';
export const ENTITY_STORE_STATUS_DELETING   = 'deleting';
export const ENTITY_STORE_STATUS_DELETED    = 'deleted';
export const ENTITY_STORE_STATUS_ERROR      = 'error';

export const ACTION_TYPE_SET_ENTITIES                   = 'ACTION_TYPE_SET_ENTITIES';
export const ACTION_TYPE_SET_ENTITIES_FILTER            = 'ACTION_TYPE_SET_ENTITIES_FILTER';
export const ACTION_TYPE_SET_ENTITIES_BUSY_INDICATION   = 'ACTION_TYPE_SET_ENTITIES_BUSY_INDICATION';
export const ACTION_TYPE_SET_ENTITIES_ERROR             = 'ACTION_TYPE_SET_ENTITIES_ERROR';

export const ACTION_TYPE_SET_SELECTED_ENTITY                    = 'ACTION_TYPE_SET_SELECTED_ENTITY';
export const ACTION_TYPE_SET_SELECTED_ENTITY_BUSY_INDICATION    = 'ACTION_TYPE_SET_SELECTED_ENTITY_BUSY_INDICATION';
export const ACTION_TYPE_SET_SELECTED_ENTITY_ERROR              = 'ACTION_TYPE_SET_SELECTED_ENTITY_ERROR';
export const ACTION_TYPE_AFTER_DELETE_ENTITY                    = 'ACTION_TYPE_AFTER_DELETE_ENTITY';

